#add_newline = false

format = """\
$username\
$hostname\
$directory\
$kubernetes\
$git_branch\
$git_state\
$git_status\
[](fg:subtext0)
$character\
  """

palette = 'catppuccin_mocha'

[character]
success_symbol = "[  ](bold fg:green)"
error_symbol = "[  ](bold fg:red)"
format = "[$symbol ❯ ](fg:subtext0)"

[cmd_duration]
min_time = 500
style = "bg:red fg:base bold"
format = "[ $duration ]($style)"

[directory]
truncation_length = 5
truncate_to_repo = true
read_only = ""
style = "fg:base bg:subtext0"
read_only_style = "fg:red bg:subtext0"
format = "[](fg:yellow bg:subtext0)[  ](bg:yellow fg:base)[](bg:subtext0 fg:yellow)[ $path]($style)[$read_only ]($read_only_style)"

[hostname]
ssh_symbol = "󰛳"
ssh_only = true
format = "[](fg:lavender bg:subtext0)[ $ssh_symbol ](bg:lavender fg:base)[](bg:subtext0 fg:lavender)[ $hostname ]($style)"
style = "bg:subtext0 fg:base"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
show_always = true
style_user = "bg:subtext0 fg:base"
style_root = "bg:subtext0 fg:base bold"
format = '[](fg:sapphire)[  ](bg:sapphire fg:base)[](bg:subtext0 fg:sapphire)[ $user ]($style)'

[kubernetes]
symbol = "󱃾"
style = "fg:base bg:subtext0"
format = '[](fg:blue bg:subtext0)[ $symbol ](bg:blue fg:base)[](bg:subtext0 fg:blue)[ $context \($namespace\) ]($style)'
disabled = false

[git_branch]
symbol = ""
style = "fg:base bg:subtext0"
format = '[](fg:sky bg:subtext0)[ $symbol ](bg:sky fg:base)[](bg:subtext0 fg:sky)[ $branch ]($style)'

[git_status]
style = "fg:base bg:subtext0"
format = '[($all_status$ahead_behind )]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
