#add_newline = false

format = """\
  $username\
  $hostname\
  $directory\
  $kubernetes\
  $git_branch\
  $git_state\
  $git_status\
  $character\
  """

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"

[cmd_duration]
min_time = 500

[directory]
truncation_length = 5
truncate_to_repo = true
read_only = "*"
style = "bold yellow"
format = "[$path]($style)[$read_only]($read_only_style) "

[hostname]
ssh_only = true
format = "@[$hostname]($style) "
style = "bold bright-green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
show_always = false
style_user = "bright-blue bold"
format = '[$user]($style)'

[kubernetes]
symbol = ""
format = ' [$context \($namespace\)]($style) '
disabled = false

[git_branch]
symbol = ""
format = '\([$branch]($style)\) '
