#add_newline = false

format = """\
  $username\
  $hostname\
  $directory\
  $kubernetes\
  $git_branch\
  $git_state\
  $git_status\
  $character\
  """

palette = 'catppuccin_mocha'

[character]
success_symbol = "[  ](bold bg:green fg:base)[](fg:green)"
error_symbol = "[  ](bold bg:red fg:base)[](fg:red)"
format = "[$symbol ](fg:subtext0)"

[cmd_duration]
min_time = 500
style = "bg:red fg:base bold"
format = "[ $duration ]($style)"

[directory]
truncation_length = 5
truncate_to_repo = true
read_only = ""
style = "fg:mantle bg:yellow"
read_only_style = "fg:red bg:yellow"
format = "[ $path]($style)[$read_only ]($read_only_style)"

[hostname]
ssh_symbol = "󰛳"
ssh_only = true
format = "[ $ssh_symbol $hostname ]($style)"
style = "bg:lavender fg:base"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
show_always = true
style_user = "bg:sapphire fg:base"
style_root = "bg:sapphire fg:base bold"
format = '[  $user ]($style)'

[kubernetes]
symbol = "󱃾"
style = "fg:crust bg:blue"
format = '[ $symbol $context \($namespace\) ]($style)'
disabled = false

[git_branch]
symbol = ""
style = "fg:base bg:sky"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:base bg:sky"
format = '[($all_status$ahead_behind )]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
