#add_newline = false

format = """\
$username\
$hostname\
$directory\
$kubernetes\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
[](fg:prev_bg)
$character\
  """

palette = 'catppuccin_mocha'

[character]
success_symbol = "[ ❯ ](bold fg:green)"
error_symbol = "[  ](bold fg:red)"
format = "[$symbol](fg:subtext0)"

[cmd_duration]
min_time = 60000
style = "fg:base bg:red"
format = "[](fg:red bg:prev_bg)[  $duration ]($style)"

[directory]
truncation_length = 5
truncate_to_repo = true
read_only = ""
style = "fg:base bg:yellow"
read_only_style = "fg:red bg:yellow"
format = "[](fg:yellow bg:prev_bg)[   $path]($style)[$read_only ]($read_only_style)"

[hostname]
ssh_symbol = "󰛳"
ssh_only = true
format = "[](fg:lavender bg:prev_bg)[ $ssh_symbol $hostname ]($style)"
style = "bg:lavender fg:base"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
show_always = true
style_user = "bg:sapphire fg:base"
style_root = "bg:sapphire fg:base bold"
format = '[](fg:sapphire)[  $user ]($style)'

[kubernetes]
symbol = "󱃾"
style = "fg:base bg:blue"
format = '[](fg:blue bg:prev_bg)[ $symbol $context \($namespace\) ]($style)'
disabled = false

[git_branch]
symbol = ""
style = "fg:base bg:sky"
format = '[](fg:sky bg:prev_bg)[ $symbol $branch ]($style)'

[git_status]
style = "fg:base bg:sky"
format = '[($all_status$ahead_behind )]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
